apiVersion: v1/beta
kind: Deployment
metadata: 
   name: Devops
spec:
   labels:
     fruit: apple
     color: red
   templates:
     name: nodejs:0.4
     labels:
       fruit: apple
       color: red
   volumes:
       emptyDir: {}
       claimName: myvol
    containers:
        name: nodejs
        image: hub.docker.io/nodejs:0.4
        ImagePullPolicy: IfNotPresent
     Files:
         name: mynode.js
         version: 1.2.1
         Tag: node1a
         
      
     
